version: "3.7"

services:
    laravel:
        build:
            args:
                user: musa
                uid: 1000
            context: .
            dockerfile: ./docker/dev-php.Dockerfile
        image: musa/laravel
        container_name: laravelapp
        restart: unless-stopped
        tty: true
        environment:
            DB_HOST: laraveldb
            DB_USERNAME: laravel
            DB_PASSWORD: password
            SESSION_DRIVER: redis
            REDIS_HOST: laravelredis
        volumes:
            - ./:/var/www:z
            - ./docker/dev-php.ini:/usr/local/etc/php/conf.d/local.ini:z
        networks:
            - laravel
        depends_on:
            - laraveldb
    
    laravelserver:
        build:
            context: .
            dockerfile: ./docker/dev-nginx.Dockerfile
        image: musa/laravelserver
        container_name: laravelserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www:z
            - ./docker/dev-nginx.conf:/etc/nginx/conf.d/default.conf:z
        networks:
            - laravel
        depends_on:
            - laravel
    
    laraveldb:
        image: mysql:5.7
        container_name: laraveldb
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
        volumes:
            - laraveldb:/var/lib/mysql
        networks:
            - laravel
    
    laravelredis:
        image: redis:latest
        container_name: laravelredis
        networks:
            - laravel

volumes:
    laraveldb:
        driver: local

networks:
    laravel:
        driver: bridge
        